### ISSUE TITLE
Radar window showing a wrong heading

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#30]
In commit 8e7ed30a125f5 the head up radar window is showing a wrong heading for the 4G radar. see picture.
![headup](https://user-images.githubusercontent.com/7831072/33028408-2d3d179c-ce16-11e7-93e4-5119f8f8dbe6.png)

In this picture trails are green, radar is single color.
Heading is 0, radar window showing 240. Overlay is OK.

**Comment by canboat** [comment]
Did you select 'disable heading on radar'? Otherwise the PPI window will prefer the radar heading, if present. This means that in emulation circumstances it is easy to get a 'strange' result...

If I use a pcap from Merrimac where I am at a known heading of 150 degrees I get 150 degrees on the PPI, so that matches.

**Comment by douwefokkema** [comment]
You are right, after all this Garmin I forgot about heading on radar on Navico (better indeed)
